CREATE DATABASE db_jb;
CREATE USER 'jbraco'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $db_jb.* TO 'jbraco'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'passwordRoot';